### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by Xayer** [nuxt-community/prismic-module#62]
Hello. I just encountered this error when using nuxt with Typescript.

`20:2 No overload matches this call.
  Overload 1 of 2, '(options: ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>> & ThisType<...>): <VC extends VueClass<...>>(target: VC) => VC', gave the following error.
    Type '({ $prismic }: { $prismic: any; }) => { posts: any; }' is not assignable to type '(ctx: Context) => void | object | Promise<void | object>'.
      Types of parameters '__0' and 'ctx' are incompatible.
        Property '$prismic' is missing in type 'Context' but required in type '{ $prismic: any; }'.
  Overload 2 of 2, '(target: VueClass<Vue>): VueClass<Vue>', gave the following error.
    Argument of type '{ asyncData({ $prismic }: { $prismic: any; }): { posts: any; }; components: { ImageBlock: typeof ImageBlock; Paragraph: typeof Paragraph; Card: typeof Card; CallToAction: typeof CallToAction; }; head: { ...; }; }' is not assignable to parameter of type 'VueClass<Vue>'.
      Object literal may only specify known properties, and 'asyncData' does not exist in type 'VueClass<Vue>'.`

My code:

``` Typescript
async asyncData ({  $prismic } : {  $prismic : any }) {
		...
}
```

My solution was to use `$prismic` like this:
``` Typescript
async asyncData () {
		const { $prismic } = Vue.prototype.$nuxt
}
```

**Comment by Atinux** [comment]
Hi @Xayer 

You should not access `Vue.prototype.$nuxt` in `asyncData`.

Actually we need to add the types for it, see how axios module do: https://github.com/nuxt-community/axios-module/tree/dev/types

PR more than welcome :)

**Comment by dertrockx** [comment]
I fixed this by creating a type definition file 
```typescript
types/prismic.d.ts
// this was from another solution, I just added because it's useful
import { getApi } from 'prismic-javascript'
import { DefaultClient } from 'prismic-javascript/types/client'

import Vue from 'vue'

type ThenArg<T> = T extends Promise<infer U> ? U : T
type PrismicAPIPromise = ReturnType<typeof getApi>
type PrismicAPI = ThenArg<PrismicAPIPromise>

type ElementType =
  | 'heading1'
  | 'heading2'
  | 'heading3'
  | 'heading4'
  | 'heading5'
  | 'heading6'
  | 'paragraph'
  | 'preformatted'
  | 'strong'
  | 'em'
  | 'list-item'
  | 'o-list-item'
  | 'group-list-item'
  | 'group-o-list-item'
  | 'image'
  | 'embed'
  | 'hyperlink'
  | 'label'
  | 'span'

type Elements = { [key in ElementType]: string }

type HTMLSerializer<T> = (type: ElementType, element: any, text: string | null, children: T[], index: number) => T

interface RichText {
  Elements: Elements
  asHtml(richText: any, linkResolver?: (doc: any) => string, serializer?: HTMLSerializer<string>): string
  asText(richText: any, joinString?: string): string
}

interface Link {
  url(link: any, linkResolver?: (doc: any) => string): string
}

interface VuePrismic {
  endpoint: string
  linkResolver: (doc: any) => string
  htmlSerializer: HTMLSerializer<string>
  client: DefaultClient
  richTextAsPlain: (field: string) => string
}

type PrismicVue<T> = VuePrismic & T

declare module 'vue/types/vue' {
  interface Vue {
    $prismic: PrismicVue<PrismicAPI>
  }
}

// here's the solution
import { getApi } from 'prismic-javascript'
import { DefaultClient } from 'prismic-javascript/types/client'

import Vue from 'vue'

type ThenArg<T> = T extends Promise<infer U> ? U : T
type PrismicAPIPromise = ReturnType<typeof getApi>
type PrismicAPI = ThenArg<PrismicAPIPromise>

type ElementType =
  | 'heading1'
  | 'heading2'
  | 'heading3'
  | 'heading4'
  | 'heading5'
  | 'heading6'
  | 'paragraph'
  | 'preformatted'
  | 'strong'
  | 'em'
  | 'list-item'
  | 'o-list-item'
  | 'group-list-item'
  | 'group-o-list-item'
  | 'image'
  | 'embed'
  | 'hyperlink'
  | 'label'
  | 'span'

type Elements = { [key in ElementType]: string }

type HTMLSerializer<T> = (type: ElementType, element: any, text: string | null, children: T[], index: number) => T

interface RichText {
  Elements: Elements
  asHtml(richText: any, linkResolver?: (doc: any) => string, serializer?: HTMLSerializer<string>): string
  asText(richText: any, joinString?: string): string
}

interface Link {
  url(link: any, linkResolver?: (doc: any) => string): string
}

interface VuePrismic {
  endpoint: string
  linkResolver: (doc: any) => string
  htmlSerializer: HTMLSerializer<string>
  client: DefaultClient
  richTextAsPlain: (field: string) => string
}

type PrismicVue<T> = VuePrismic & T

declare module 'vue/types/vue' {
  interface Vue {
    $prismic: PrismicVue<PrismicAPI>
  }
}

```

**Comment by lihbr** [comment]
Hey, I guess it was from here: https://github.com/prismicio/prismic-vue/issues/5, really looking forward to move our kit to typescript properly this year ☺️

**Comment by lihbr** [comment]
*Update `05/04/2021`:*
1. TypeScript support will be improved as part of the module v2 once we're done refreshing @prismicio/client: https://github.com/prismicio/prismic-javascript/issues/163. We already made some progress on it when working on our Vue 3 plugin: https://prismic-vue-next.netlify.app

**Comment by lihbr** [comment]
The new version of the module targetting Nuxt 3 comes with first-class TypeScript support 🎉

https://v3.prismic.nuxtjs.org/

**Comment by simonmaass** [comment]
@lihbr i am using nuxt 2 and I followed this solution: https://github.com/prismicio/prismic-vue/issues/5#issuecomment-723652806

I added a prismic.d.ts file in the /types folder... but i am still not able to access $prismic... do you have an idea?

**Comment by simonmaass** [comment]
@lihbr this is my component

![image](https://github.com/nuxt-modules/prismic/assets/32599710/882f404c-a389-4b91-90eb-65105fe7949f)

This is the folder structure:

<img width="206" alt="image" src="https://github.com/nuxt-modules/prismic/assets/32599710/4a4d9e72-5f90-4f1f-a24e-e5798d18890b">

with this content: https://github.com/nuxt-modules/prismic/issues/62#issuecomment-755076873

I think it is related to me using the composition api and the setup function... any ideas?

**Comment by lihbr** [comment]
Thems for sharing details ! Shouldn't it be `this.$prismic` inside class components ? Not sure how well this plays with Vue 2 composition API 🤔

**Comment by simonmaass** [comment]
then i get this:
<img width="563" alt="image" src="https://github.com/nuxt-modules/prismic/assets/32599710/df46e753-d5f0-44d1-9c5a-79c84f558302">

what is weird is that this works:
<img width="488" alt="image" src="https://github.com/nuxt-modules/prismic/assets/32599710/65cfff18-a3ea-48e1-8d00-75f0e2219ca6">

**Comment by lihbr** [comment]
OK, correct, `this` is not available with composition API, maybe `useContext().app.$prismic` or `useNuxtApp().$prismic` (that's how you'd do it in Nuxt 3 when not using `usePrismic()` directly)

**Comment by simonmaass** [comment]
yeah that works! thnx!

**Comment by lihbr** [comment]
Awesome 🔥
