### ISSUE TITLE
Error: Can't resolve 'prismic-vue/components/common' on 1.1.1

### ISSUE THREAD

**Issue by carlos-avila** [nuxt-community/prismic-module#70]
### Error Message

ERROR in ./.nuxt/prismic/plugins/prismic-components.js
Module not found: Error: Can't resolve 'prismic-vue/components/common' in '/home/cavila/repositories/mandelbrew-local-biz-gifts/.nuxt/prismic/plugins'

### Fix 
This seems to be fixed in [643186f](https://github.com/nuxt-community/prismic-module/commit/643186f7857470e8546ea5c339cd3d1d623254ce)

Is there any way to add this fix to 1.1.1? as it stands, 1.1.1 is broken.

**Comment by cannap** [comment]
i had the same 

just add 

prismic-dom
prismic-javascript
prismic-vue

to your project but i think you just need prismic-vue for the components

**Comment by hypervillain** [comment]
Heys, I think it's been fixed and merged.
@Atinux will probably publish soon

**Comment by cannap** [comment]
the real prismic-vue package add this only as peerDepen... so you need to add it anyway

**Comment by Atinux** [comment]
Fixed in https://github.com/nuxt-community/prismic-module/releases/tag/v1.2.1, sorry about this

**Comment by jameshhood** [comment]
I'm having an issue with @prismicio/vue/components/common

``` ERROR  Failed to compile with 1 errors                                                                                                                        friendly-errors 19:00:55

This dependency was not found:                                                                                                                                 friendly-errors 19:00:55
                                                                                                                                                               friendly-errors 19:00:55
* @prismicio/vue/components/common in ./.nuxt/prismic/plugins/prismic-components.js

**Comment by hypervillain** [comment]
Can you `yarn add @prismicio/vue` @jameshhood ?

**Comment by jameshhood** [comment]
@hypervillain Yeah I was able to install `@prismicio/vue v2.0.6`. I cleaned my node_modules and my .nuxt output and it still happens. In my node_modules in the `@prismicio/vue` directory, it only has a `dist` and a `src` directory in it so I'm not even sure what `prismic/plugins/prismic-components.js` is even looking for

**Comment by hypervillain** [comment]
Oh ok indeed, I pulled everything and republished the components (https://unpkg.com/@prismicio/vue@2.0.7/components/common.js), sorry for the inconvenience

**Comment by simonmaass** [comment]
` ERROR  Failed to compile with 1 errors                                                                                                                                                     friendly-errors 10:11:43  

This dependency was not found:                                                                                                                                                              friendly-errors 10:11:43  
                                                                                                                                                                                            friendly-errors 10:11:43  
* @prismicio/vue/components/common in ./.nuxt/prismic/plugins/prismic-components.js                                                                                                         friendly-errors 10:11:43  
                                                                                                                                                                                            friendly-errors 10:11:43  
To install it, you can run: npm install --save @prismicio/vue/components/common`

i am getting this in "@nuxtjs/prismic": "^1.2.4",

**Comment by lihbr** [comment]
Hey @simonmaass, @juDmnca really sorry for the inconvenience! We apparently had an issues with our build when releasing @prismicio/vue@2.0.8 yesterday, we released a fix! Update it with:
```bash
$ yarn upgrade @prismicio/vue@^2.0.9
# or
$ npm update @prismicio/vue@^2.0.9
```
If you're still experiencing the issue try deleting your node modules and lock file and install everything again! Thanks 🙏

**Comment by simonmaass** [comment]
works again - thnx!
